#info
info:
  app:
    name: ${spring.application.name}
    instance: ${eureka.instance.instance-id}
    department: @department.name@
    developer: @developer.name@

#server
server:
  port: ${server.port}
#eureka
eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true

#spring
spring:
  jmx:
    enabled: true
  mvc:
    static-path-pattern: /**
    servlet:
      load-on-startup: 1
  sleuth:
    sampler:
      percentage: 1.0
  http:
    multipart:
      location: /opt/webapps/ZuulGateway/temp/
      max-file-size: 5MB
      max-request-size: 10MB


#https://github.com/javamelody/javamelody/wiki/SpringBootStarter
javamelody:
  advisor-auto-proxy-creator-enabled: false
  init-parameters:
    authorized-users: springcloud:springcloud123456
    storage-directory: logs/javamelody
    warning-threshold-millis: 200
    severe-threshold-millis: 500