#info
info:
  app:
    name: ${spring.application.name}
    instance: ${eureka.instance.instance-id}
    department: @department.name@
    developer: @developer.name@

#server
server:
  port: ${server.port}
#feign
feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 60000
#ribbon
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  #ReadTimeout: 60000
  #ConnectTimeout: 60000

#hystrix
hystrix:
  command:
    default:
      execution:
        isolation:
           thread:
             timeoutInMilliseconds: 60000
    lyqc-loan-fws-web:
      execution:
        isolation:
           thread:
             timeoutInMilliseconds: 60000
#eureka
eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true

#spring
spring:
  jmx:
    enabled: true
  mvc:
    static-path-pattern: /**
    servlet:
      load-on-startup: 1
  sleuth:
    sampler:
      percentage: 1.0
  http:
    multipart:
      location: /opt/webapps/ZuulGateway/temp/
      max-file-size: 5MB
      max-request-size: 10MB


#https://github.com/javamelody/javamelody/wiki/SpringBootStarter
javamelody:
  advisor-auto-proxy-creator-enabled: false
  init-parameters:
    authorized-users: springcloud:springcloud123456
    storage-directory: logs/javamelody
    warning-threshold-millis: 200
    severe-threshold-millis: 500

#安全认证 https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-monitoring.html
management:
  security:
    enabled: true
  info:
    git:
      mode: full
security:
  user:
    name: springcloud
    password: springcloud123456
  basic:
    enabled: false
#endpoints
endpoints:
  enabled: false
  env:
    enabled: true
    sensitive:
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false

#http://cloud.spring.io/spring-cloud-static/Edgware.RELEASE/single/spring-cloud.html#_router_and_filter_zuul
zuul:
  retryable: false
  add-host-header: true
  ignored-services: '*'
  routes:
    lyqc-loan-fws-web: /lyqcfws/**